### ISSUE TITLE
hardbin.com can be used to view any IPFS address

### ISSUE THREAD

**Issue by icefoxen** [jes/hardbin#3]
Just paste in the one you want and it fetches arbitrary IPFS documents, for example https://hardbin.com/ipfs/Qmbg9p7V6gK58HdGFc7oe9YDyMfXtuytNYUzwbGktc6g1q

This is probably kind of intrinsic to how it works, and you probably realize this already, but it's a sort of weird edge case that I didn't expect to work but does.

**Comment by jes** [comment]
Not a bug, this is in fact intended behaviour: hardbin.com is a public writeable IPFS gateway :)

**Comment by icefoxen** [comment]
Just making sure.  :D
