### ISSUE TITLE
Which chrome extension to recommend?

### ISSUE THREAD

**Issue by qm3ster** [jes/hardbin#5]
There's [IPFS Companion](https://github.com/ipfs-shipyard/ipfs-companion) and [IPFS Station](https://github.com/fbaiodias/ipfs-chrome-station) on the chrome store. Which one is better and why?

**Comment by victorb** [comment]
AFAIK, IPFS Station is not being updated anymore. IPFS Companion is under the ipfs-shipyard organization and still maintained, so I would go for Companion today.

**Comment by jes** [comment]
Thanks, I updated this in b6fd0d309e9711f14b3d8e3d07571e4731a715ea

**Comment by qm3ster** [comment]
I thought I ~deleted~closed this fast enough.
Someone must check their emails or something.
Well, I have no one but myself to blame for b6fd0d3.
gg wp
